<?php
$estruturaColuna = function($label, $coluna_nome) {
    $html = '';
    $html .= "<a title='Ordenar por $coluna_nome' href='{$this->url('alunos', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_nome' => $coluna_nome, 'coluna_sort' => ($this->coluna_nome != $coluna_nome ? 'ASC' : ($this->coluna_sort == 'DESC' ? 'ASC' : 'DESC')), 'itens_pagina' => $this->itens_pagina, 'search' => $this->search]])}'>";
 
    if ($this->coluna_nome == $coluna_nome) {
        $icon = $this->coluna_sort == 'ASC' ? '' : '-alt';
        $html .= "<span class='glyphicon glyphicon-sort-by-attributes{$icon}'></span> ";
    }
 
    $html .= $label;
 
    return $html;
};
?>
<tr>
    <th>
        <?php echo $estruturaColuna('Nº Registro', 'id'); ?>
    </th>
    <th>
        <?php echo $estruturaColuna('Nome', 'nome'); ?>
    </th>
    <th>
        Tel. Principal
    </th>
    <th>
        Tel. Qua.
    </th>
    <th>
        <?php echo $estruturaColuna('Dt. Cadastro', 'data_cadastro'); ?>
    </th> 
    <th>Ação</th>  
</tr>