<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Detalhes Contrato Nº <?php echo $this->filterContrato($data)->id(); ?>      
        </div>
        
         <?php $alunos = $this->alunos; ?>
        
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Aluno:</dt>
            <dd><?php echo $this->filterContrato($data, $alunos)->alunoCompleto(); ?></dd>
            <dt>Valor:</dt>
            <dd><?php echo $this->filterContrato($data)->valor(); ?></dd>
            <dt>Quantidade de Meses:</dt>
            <dd><?php echo $this->filterContrato($data)->quantMeses(); ?></dd>
            <dt>Data Inicial:</dt>
            <dd><?php echo $this->filterContrato($data)->dataInicio(); ?></dd>
            <dt>Data de Vencimento:</dt>
            <dd><?php echo $this->filterContrato($data)->dataFim(); ?></dd>
            <dt>Data de Cadastro:</dt>
            <dd><?php echo $this->filterContrato($data)->dataCadastro(); ?></dd>
            <dt>Data de Atualização:</dt>
            <dd><?php echo $this->filterContrato($data)->dataAlteracao(); ?></dd>
        </dl>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('contratos', array('action' => 'editar', 'id' => $this->filterContrato($data)->id())); ?>" class="btn btn-warning btn-sm">Editar Contrato</a>
        <a href="<?php echo $this->url('contratos'); ?>" class="btn btn-default btn-sm">Voltar</a>
    </div>
</div>