<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Detalhes Contrato Nº <?php echo $this->filterContrato($data)->id(); ?>      
        </div>
        
         <?php $alunos = $this->alunos; ?>
        
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Nº Contrato:</dt>
            <dd><?php echo $this->filterContrato($data, $alunos)->id(); ?></dd>
            <dt>Aluno:</dt>
            <dd><?php echo $this->filterContrato($data, $alunos)->alunoCompleto(); ?></dd>
            <dt>Valor:</dt>
            <dd><?php echo $this->filterContrato($data)->valor(); ?></dd>
            <dt>Valor aula teórica:</dt>
            <dd><?php echo $data->valor_aula_teorica; ?></dd>
            <dt>Valor aula (carro):</dt>
            <dd><?php echo $data->valor_aula_carro; ?></dd>
            <dt>Valor aula (moto):</dt>
            <dd><?php echo $data->valor_aula_moto; ?></dd>
            <dt>Quantidade de Meses:</dt>
            <dd><?php echo $this->filterContrato($data)->quantMeses(); ?></dd>
            <dt>Data Inicial:</dt>
            <dd><?php echo $this->filterContrato($data)->dataInicio(); ?></dd>
            <dt>Data de Vencimento:</dt>
            <dd><?php echo $this->filterContrato($data)->dataFim(); ?></dd>
            <dt>Data de Cadastro:</dt>
            <dd><?php echo $this->filterContrato($data)->dataCadastro(); ?></dd>
            <dt>Data de Atualização:</dt>
            <dd><?php echo $this->filterContrato($data)->dataAlteracao(); ?></dd>
        </dl>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('contratos'); ?>" class="btn btn-default btn-sm">Voltar</a>
        <a href="<?php echo $this->url('contratos', array('action' => 'editar', 'id' => $this->filterContrato($data)->id())); ?>" class="btn btn-warning btn-sm">Editar Contrato</a>
        <a href='<?php echo $this->url('contratos', array('action' => 'deletar', 'id' => $data->id)); ?>' class='btn btn-danger btn-sm'>Excluir Contrato</a>
        <a href='<?php echo $this->url('contratos', array('action' => 'visualizar', 'id' => $data->id)); ?>' target="_blank" class='btn btn-default btn-sm'>Visualizar Contrato</a>
        <a href='<?php echo $this->url('contratos', array('action' => 'salvarpdf', 'id' => $data->id)); ?>' class='btn btn-default btn-sm'>Salvar em PDF</a>     
    </div>
</div>



<?php $this->headScript()->captureStart(); ?>
$(function(){
    // variável para conter a url deletar
    var url_deletar     = '<?php echo $this->url('contratos', array("action" => "deletar")); ?>' + '/';
 
    // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
    $("a[href*='" + url_deletar + "']").click(function (event) {
        // variável contendo o id referente ao botão clicado
        var aluno_id  = $(this).attr('href').split(url_deletar).pop();
        // variável contendo mensagem da janela
        var mensagem = "Deseja realmente apagar o contrato de ID " + aluno_id + "?";
        // variável com resposta da mensagem colocada na janela
        var confirmacao = confirm(mensagem);
 
        // se a confirmação for false o fluxo é interrompido
        if (!confirmacao)
            // elimar o evendo do botão clicado
            event.preventDefault();
    });
});
<?php $this->headScript()->captureEnd(); ?>