<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Editar Contrato      
        </div>
    </div>
    <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url('contratos', ['action' => 'atualizar']));
        echo $this->form()->openTag($form) 
    ?>
    <form class="form-horizontal" role="form" method="post" action="<?php echo $this->url('contratos', array('action' => 'atualizar')); ?>">
        
        <div class="panel-body">
            
            
            <div class="form-group">
                <label for="valor" class="col-lg-3 col-md-3 control-label">Valor:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('valor')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('valor'));
                    ?>
                </div>
            </div>
            
            <div class="form-group">
                <label for="valor_aula_teorica" class="col-lg-3 col-md-3 control-label">Valor aula teórica:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('valor_aula_teorica')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('valor_aula_teorica'));
                    ?>
                </div>
            </div>
            
            <div class="form-group">
                <label for="valor_aula_carro" class="col-lg-3 col-md-3 control-label">Valor aula carro:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('valor_aula_carro')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('valor_aula_carro'));
                    ?>
                </div>
            </div>
            
            <div class="form-group">
                <label for="valor_aula_moto" class="col-lg-3 col-md-3 control-label">Valor aula moto:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('valor_aula_moto')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('valor_aula_moto'));
                    ?>
                </div>
            </div>
            
            
            <div class="form-group">
                <label for="data_inicio" class="col-lg-3 col-md-3 control-label">Data Inicial:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('data_inicio')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('data_inicio'));
                    ?>
                </div>
            </div>
            
            <div class="form-group">
                <label for="data_fim" class="col-lg-3 col-md-3 control-label">Data de Vencimento:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('data_fim')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('data_fim'));
                    ?>
                </div>
            </div>
            
        </div>
        <div class="panel-footer">
            <?php
                echo $this->formHidden($form->get('aluno_id'));
                echo $this->formHidden($form->get('quant_meses'));
                echo $this->formHidden($form->get('id'));
                echo $this->formElement($form->get('security')); 
            ?>
            <button type="submit" class="btn btn-primary">Atualizar Contrato</button>
            <a href="<?php echo $this->url('contratos'); ?>" class="btn btn-default">Voltar</a>
        </div>
    <?php echo $this->form()->closeTag() ?>
</div>