<div class="topo-table">
    <a href="<?php echo $this->url('contratos', array('action' => 'novo')); ?>" class="btn btn-success" title="Novo"><span class="glyphicon glyphicon-plus"></span></a>
 
    <div class="btn-group" title="Itens por Página">
        <button type="button" class="btn btn-default"><?php echo $this->itens_pagina?></button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right" style="min-width: 75px" role="menu">
            <?php foreach (['1','5', '10', '25', '50', '100'] as $value): ?>
                <li class="<?php echo ($this->itens_pagina == $value ? 'active' : ''); ?>"><a href="<?php echo $this->url('contratos', ['action' => 'index'], ['query' => ['pagina' => $this->pagina_atual, 'coluna_nome' => $coluna_nome, 'coluna_sort' => $this->coluna_sort, 'itens_pagina' => $value, 'search' => $this->search]])?>"><?php echo $value;  ?></a></li>
            <?php endforeach;?>
        </ul>
    </div>
 
    <form class="form-inline pull-right" role="form">
        <div class="form-group">
            <label class="sr-only" for="localizar">Buscar...</label>
            <input type="search" name="search" value="<?php echo $this->search; ?>" class="form-control" id="localizar" placeholder="Bucar...">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
    </form>
</div>
 
<br />
 
<div class="corpo-table">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <?php echo $this->partial('partial/colunas_sort_contratos'); ?>
        </thead>
 
       
<tbody>
    <?php foreach ($this->data as $dados) : ?>
        <tr>
            <td class="text-center"><?php echo $dados->id; ?></td>
            <td class="text-center"><?php echo $dados->valor; ?></td>
            <td class="text-center"><?php echo $dados->data_inicio; ?></td>
            <td class="text-center"><?php echo $dados->data_fim; ?></td>
            <td class="text-center"><?php echo $dados->data_cadastro; ?></td>
            <td class="text-center"><?php echo $dados->quant_meses; ?></td>
            <td>
                <a class="btn btn-xs btn-info" title="Visualizar" href="<?php echo $this->url('contratos', array("action" => "detalhes", "id" => $dados->id,)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('contratos', array("action" => "editar", "id" => $dados->id,)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('contratos', array("action" => "deletar", "id" => $dados->id,)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
            </td>
        </tr>
    <?php endforeach; ?>
</tbody>
    </table>
 
    

    <?php
    // controle de paginação
    echo $this->paginationControl(
        // objeto contentdo os contatos
        $this->data,

        // tipo de style da paginação
        'Sliding',

        // partial que vai conter o html da paginação
        [/*path*/ 'partial/paginator.phtml', /*modulo*/ 'Aluno'],

        // link rotas da paginação
        ['route' => 'contratos']
    );
    ?>
    
</div>






<?php $this->headScript()->captureStart(); ?>
$(function(){
    // variável para conter a url deletar
    var url_deletar     = '<?php echo $this->url('contratos', array("action" => "deletar")); ?>' + '/';
 
    // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
    $("a[href*='" + url_deletar + "']").click(function (event) {
        // variável contendo o id referente ao botão clicado
        var aluno_id  = $(this).attr('href').split(url_deletar).pop();
        // variável contendo mensagem da janela
        var mensagem = "Deseja realmente apagar o aluno de ID " + aluno_id + "?";
        // variável com resposta da mensagem colocada na janela
        var confirmacao = confirm(mensagem);
 
        // se a confirmação for false o fluxo é interrompido
        if (!confirmacao)
            // elimar o evendo do botão clicado
            event.preventDefault();
    });
});
<?php $this->headScript()->captureEnd(); ?>