<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Detalhes Aluno ID <?php echo $this->escapeHtml($this->id); ?>            
        </div>
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Nome:</dt>
            <dd><?php echo $this->escapeHtml($this->form["nome"]); ?></dd>
            <dt>Telefone Principal:</dt>
            <dd><?php echo $this->escapeHtml($this->form["telefone"]); ?></dd>
            <dt>Telefone Secundario:</dt>
            <dd><?php echo $this->escapeHtml($this->form["telefone2"]); ?></dd>
            <dt>Data Criação:</dt>
            <dd><?php echo $this->escapeHtml($this->form["data_cadastro"]); ?></dd>
            <dt>Data Atualização:</dt>
            <dd><?php echo $this->escapeHtml($this->form["data_alteracao"]); ?></dd>
        </dl>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('alunos', array('action' => 'editar', 'id' => $this->id)); ?>" class="btn btn-warning btn-sm">Editar Aluno</a>
        <a href="<?php echo $this->url('alunos'); ?>" class="btn btn-default btn-sm">Voltar</a>
    </div>
</div>