<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Editar Aluno 
        </div>
    </div>
    <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url('alunos', ['action' => 'atualizar']));
        echo $this->form()->openTag($form) 
    ?>
    <form class="form-horizontal" role="form" method="post" action="<?php echo $this->url('alunos', array('action' => 'atualizar')); ?>">
        
        <div class="panel-body">
            <div class="form-group">
                <label for="nome" class="col-lg-3 col-md-3 control-label">Nome:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('nome')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('nome'));
                    ?>
                </div>
            </div>
            
            <div class="form-group">
                <label for="end_rua" class="col-lg-3 col-md-3 control-label">Endereço:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('end_rua')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('end_rua'));
                    ?>
                    
                </div>
            </div>
            
            <div class="form-group">
                <label for="end_bairro" class="col-lg-3 col-md-3 control-label">Bairro:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('end_bairro')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('end_bairro'));
                    ?>
                    
                </div>
            </div>
            
            <div class="form-group">
              <label for="end_cidade" class="col-lg-3 col-md-3 control-label">Cidade:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('end_cidade')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('end_cidade'));
                    ?>
                </div>
            </div>
            
            <div class="form-group">
              <label for="end_estado" class="col-lg-3 col-md-3 control-label">Estado:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('end_estado')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('end_estado'));
                    ?>
                </div>
            </div>
            
            <div class="form-group">
              <label for="cpf" class="col-lg-3 col-md-3 control-label">CPF:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('cpf')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('cpf'));
                    ?>
                </div>
            </div>
            
            <div class="form-group">
                <label for="email" class="col-lg-3 col-md-3 control-label">Email:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('email')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('email'));
                    ?>
                </div>
            </div>
            
            <div class="form-group">
                <label for="sexo" class="col-lg-3 col-md-3 control-label">Sexo:</label>
                <div class="col-lg-9 col-md-9">
                    <?php echo $this->formInput($form->get('sexo')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('sexo'));
                    ?>
                </div>
            </div>
            
 
            <div class="form-group">
                <label for="telefone" class="col-lg-3 col-md-3 control-label">Tel. Principal:</label>
                <div class="col-lg-9  col-md-9">
                    <?php echo $this->formInput($form->get('telefone')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('telefone'));
                    ?>
                </div>
            </div>
 
            <div class="form-group">
                <label for="telefone2" class="col-lg-3 col-md-3 control-label">Tel. Secundário:</label>
                <div class="col-lg-9  col-md-9">
                    <?php echo $this->formInput($form->get('telefone2')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('telefone2'));
                    ?>
                </div>
            </div>
            
            <div class="form-group">
                <label for="data_nascimento" class="col-lg-3 col-md-3 control-label">Data de Nascimento:</label>
                <div class="col-lg-9  col-md-9">
                    <?php echo $this->formInput($form->get('data_nascimento')); 
                        // renderiza elemento de erro
                        echo $this->formElementErrors()
                        ->setMessageOpenFormat('<small class="text-danger">')
                        ->setMessageSeparatorString('</small><br/><small class="text-danger">')
                        ->setMessageCloseString('</small>')
                        ->render($form->get('data_nascimento'));
                    ?>
                </div>
            </div>
            
        </div>
        <div class="panel-footer">
            <?php
                echo $this->formHidden($form->get('id'));
                echo $this->formElement($form->get('security')); 
            ?>
            <button type="submit" class="btn btn-primary">Atualizar Cadastro</button>
            <a href="<?php echo $this->url('alunos'); ?>" class="btn btn-default">Voltar</a>
        </div>
    <?php echo $this->form()->closeTag() ?>
</div>