<div class="panel panel-primary">
    <div class="panel-heading">
        <div class="panel-title">
            Editar Aluno ID <?php echo $this->id; ?>        
        </div>
    </div>
    <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('alunos', array('action' => 'atualizar')); ?>">
        <div class="panel-body">
            <div class="form-group">
                <label for="inputNome" class="col-lg-3 col-md-3 control-label">Nome:</label>
                <div class="col-lg-9 col-md-9">
                    <input type="text" name="nome" class="form-control" id="inputNome" placeholder="Nome Completo" value="<?php echo $this->escapeHtml($this->form['nome']); ?>">
                </div>
            </div>
 
            <div class="form-group">
                <label for="inputTelefone" class="col-lg-3 col-md-3 control-label">Tel. Principal:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="telefone" class="form-control" id="inputTelefone" placeholder="Digite seu telefone principal" value="<?php echo $this->escapeHtml($this->form['telefone']); ?>">
                </div>
            </div>
 
            <div class="form-group">
                <label for="inputTelefone2" class="col-lg-3 col-md-3 control-label">Tel. Secundário:</label>
                <div class="col-lg-9  col-md-9">
                    <input type="text" name="telefone2" class="form-control" id="inputTelefone2" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['telefone']); ?>">
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <input type="hidden" name="id" value="<?php echo $this->id; ?>">
            <button type="submit" class="btn btn-primary">Atualizar Cadastro</button>
            <a href="<?php echo $this->url('alunos'); ?>" class="btn btn-default">Voltar</a>
        </div>
    </form>
</div>