<h1 class="text-center">EM CONSTRUÇÃO..</h1>

<h4>Últimos alunos cadastrados</h4>
<ul>
<?php 
    foreach($this->alunos as $aluno): ?>
        <li>
            <?php echo $aluno->nome; ?>
        </li>
   <?php endforeach; ?>
</ul>


<h4>Últimos contratos cadastrados</h4>
<ul>
<?php 
    foreach($this->contratos as $contrato): ?>
        <li>
            <?php echo $contrato->id; ?>
        </li>
   <?php endforeach; ?>
</ul>